### ISSUE TITLE
the pip documentation implementation breaks with : TypeError: must be str, not list

### ISSUE THREAD

**Issue by pinikomarov** [zahlabut/LogToolPyPi#1]
using the conf.ini from : 
https://github.com/zahlabut/LogTool/blob/master/LogTool_Package/conf.ini

the pip documentation implementation breaks with : 

In [1]: from zahlabut.LogTool import *               # To import all from zahlabut LogTool package                     

In [2]: load_conf_file('conf.ini')                   # To load the cofiguration file (conf.ini).                       
Provided configuration file is: conf.ini

In [3]: load_conf_file('conf.ini')                   # To load the cofiguration file (conf.ini).                       
Provided configuration file is: conf.ini

In [4]: result=start_analyzing()                     # Start analyzing log files.                                      
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-cf26ff377c7b> in <module>
----> 1 result=start_analyzing()                     # Start analyzing log files.

~/tobiko_venv/lib/python3.6/site-packages/zahlabut/LogTool.py in start_analyzing()
    601         LogTool.empty_file_content(LogTool.log_tool_result_file)
    602     start_time=time.time()
--> 603     logs=LogTool.collect_log_paths(LogTool.log_root_dir, LogTool.logs_to_ignore)
    604     for log in logs:
    605         obj=LogTool(log)

~/tobiko_venv/lib/python3.6/site-packages/zahlabut/LogTool.py in collect_log_paths(log_root_dir, logs_to_ignore)
    130                 filtered_logs.append(log)
    131         if len(filtered_logs)==0:
--> 132             sys.exit('Failed - No log files detected in: '+log_root_dir)
    133         return filtered_logs
    134 
TypeError: must be str, not list

**Comment by pinikomarov** [comment]
replacing with :  log_root_dir = '/var/log/containers' in conf ini , resolves it

**Comment by zahlabut** [comment]
Fixed
